server:
  port: 8080

# MySql数据连接设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/court?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis:
      # Redis数据库索引（默认为0）
      database: 0
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1ms
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0



# MyBatis设置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.springboot.domain

#showSql
logging:
  level:
    com:
      example: debug
    root: info




